version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Socket Docker pour exécuter des conteneurs
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    networks:
      - pentestnet

  # Ces services sont définis comme des images à utiliser par le backend
  nmap_worker:
    build:
      context: ./workers/nmap
    networks:
      - pentestnet

  nuclei_worker:
    build:
      context: ./workers/nuclei
    networks:
      - pentestnet

  nikto_worker:
    build:
      context: ./workers/nikto
    networks:
      - pentestnet

networks:
  pentestnet: